---
title: "Birth model - Clue dataset"
author: "Laura Symul"
date: "4/18/2019"
output: html_document
---

```{r birth_model_kindara setup, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
source("Scripts/00_setup.R")
```


## Clue dataset


### Model S+9

```{r load the data}

pp = read_feather(path = str_c(IO$output_clue,"pop_indicators/relative_sexual_indicators_detrended.feather"))

load(str_c(IO$out_Rdata,"birth_data.Rdata"), verbose = TRUE)

```

```{r get the relative amplitude of r_unprot}

pp = pp %>% group_by(country_area, BC) %>% mutate(av_trend_unprot = mean(trend_r_unprot)) %>% 
  mutate(x_unprot = detrended_r_unprot / av_trend_unprot)

ggplot(pp, aes(x = date, y = x_unprot, col = BC))+
  geom_line(alpha = 0.75)+ expand_limits(y = c(-1,1))+
  facet_grid(country_area ~ . , scale = "free")

```

```{r births, fig.width=5}

birth = birth %>% mutate(
  country_area = ifelse(area == "Whole country", str_c(country), str_c(country, " - ", area))
)

B = birth %>% dplyr::filter(country_area %in% pp$country_area) %>% 
  group_by(country_area) %>% dplyr::summarize(
    n_month = n(),
    n_birth = sum(births),
    ave_daily_birth = n_birth/n_month/30.5)

pp$B0 = B$ave_daily_birth[match(pp$country_area, B$country_area)]

# I still need to pull the data for the different census region in the US

N = 30
gestation_distribution = dnorm(-N:N,mean = 0, sd = 9) # same here, this is more or less realistic, but we can pull actual gestation length data

filter_2 = function(x, filter, N, by = 0*x){
  foreach(b = unique(by), .combine = c) %do% {
    this_x = x[by == b]
    xx = c(rev(this_x[1:N]),this_x, rev(this_x[(length(this_x)-N+1):length(this_x)]))
    y = stats::filter(x = xx, filter = gestation_distribution)
    y = y[!is.na(y)]
    if(all(is.na(this_x))){y = this_x}
    return(y)
  }
}

births = pp %>% dplyr::select(date, country_area, BC, detrended_r_unprot, x_unprot, B0) %>% 
  mutate(date_conception = date, 
         date = date + months(9),
         conceptions = B0 * (1+x_unprot)) %>% 
  arrange(country_area, BC, date) %>% 
  mutate(births = filter_2(x = conceptions, filter = gestation_distribution, N = N, by = interaction(country_area, BC)))

ggplot(births, aes(x = date, y = births, col = BC))+
  geom_hline(aes(yintercept = B0), col = "gray50")+
  geom_line(alpha = 0.75)+
  expand_limits(y = 0)+
  facet_grid(country_area ~ . , scale = "free_y")
  
ca = unique(births$country_area)
birth$date = as.Date(birth$date)
ggplot(birth %>% dplyr::filter(country_area %in% ca, date > as.Date("2014-01-01")), 
       aes(x = date, y = births))+
  geom_line()+expand_limits(y = 0)+
  facet_grid(country_area ~ . , scale = "free_y")
  

monthly_births = births %>% mutate(month = month(date),
                                   year = year(date),
                                   year_month = year + (month-1)/12) %>% 
  group_by(country_area, BC, year_month) %>% dplyr::summarise_each(funs = sum, births, conceptions)
  


ggplot(monthly_births, aes(x = year_month, y = births, col = BC))+
  geom_line(alpha = 0.75)+
  expand_limits(y = 0)+
  facet_grid(country_area ~ . , scale = "free_y")
  

```








```{r eval = FALSE, include = FALSE}


j = (births$country_area == "France") & (births$BC == "F")

x00 = births$detrended_r_unprot[j]
x0 = births$x_unprot[j]
c = births$conceptions[j]
x1 = births$births[j]
y1 = filter_2(x = c, filter = gestation_distribution, N = N, by = 0*c)

j = (births$country_area == "United States - California") & (births$BC == "F")

c = births$conceptions[j]
x2 = births$births[j]
y2 = filter_2(x = c, filter = gestation_distribution, N = N, by = 0*c)


plot(x1, type = "l", ylim = range(c(0,x1,x2)))
points(y1, type = "l", lty = 2, col = "red")
points(x2, type = "l", col = "blue")
points(y2, type = "l", lty = 2, col = "green")

```


```{r eval = FALSE, include = FALSE}
t = 1:120
x0 = 2
rel_ampl = 0.5
x = x0 * (1 + rel_ampl*cos(t/30*2*pi))
plot(x, type = "b")
xts = ts(x, frequency = 30)
stlx = stl(xts, s.window = "periodic")
plot(stlx)

plot(stlx$time.series[,1]/stlx$time.series[,2], type = "b")

```


```{r eval = FALSE, include = FALSE}

x = sample(0:1, 20, replace = TRUE)
plot(x, type = "b")

f = c(1/4,1/2,1/4)

y = stats::filter(x = c(0,x,0), filter = f)

plot(x, type = "b")
points(y[!is.na(y)], type = "b", col = "red")


```

