---
title: "Presenting the datasets"
author: "Laura Symul"
date: "4/18/2019"
output: html_document
---

```{r data_presentation setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Scripts/00_setup.R")
```


## Datasets and user's demographics

### Clue


```{r data_presentation load data}
users = read_feather(path = paste0(IO$output_clue, "users.feather"))
```


```{r data_presentation population overview}
users$country_area = factor(users$country_area, levels = names(sort(table(users$country_area))))
ggplot(users, aes(x = reorder(country_area,desc(country_area)), fill = country_area)) + coord_flip() + geom_bar() + guides(fill = FALSE) + 
  xlab("") + ylab("# of users") + ggtitle("# of users per country") 

ggplot(users, aes(x = birth_year_bin, fill = country_area)) + geom_bar() + facet_grid(country_area ~ ., scale = "free_y") + guides(fill = FALSE) + xlab("") + ylab("# of users") +
  ggtitle("Birth year (Age) distribution")
ggplot(users, aes(x = height_bin, fill = country_area)) + geom_bar() + facet_grid(country_area ~ ., scale = "free_y") + guides(fill = FALSE) + xlab("") + ylab("# of users") + 
  ggtitle("Users' height distribution")
ggplot(users, aes(x = weight_bin, fill = country_area)) + geom_bar() + facet_grid(country_area ~ ., scale = "free_y") + guides(fill = FALSE)+ xlab("") + ylab("# of users") + 
  ggtitle("Users' weight distribution")
ggplot(users, aes(x = est_mean_bmi, fill = country_area)) +  geom_histogram(binwidth = 2) + facet_grid(country_area ~ ., scale = "free_y") + guides(fill = FALSE)+ xlab("") + ylab("# of users") + 
  ggtitle("Users' approx. BMI distribution")

users$latest_birth_control = factor(users$latest_birth_control, levels = names(sort(table(users$latest_birth_control))))
ggplot(users, aes(x = latest_birth_control, fill = country_area)) + coord_flip() + geom_bar()+ guides(fill = FALSE) +  xlab("") + ylab("# of users") + ggtitle("Distribution of Birth Control")
```

