---
title: "Results: Synchronicity in period?"
author: "Laura Symul"
date: "4/18/2019"
output: html_document
---

```{r results_sex setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Scripts/00_setup.R")
```


## Do sexual intercourse patterns drive birth seasonal rhythms?

### Clue


```{r results_sex load data}

tt = read_feather(str_c(IO$output_clue,"pop_indicators/","relative_sexual_indicators_overall_by_country.feather"))
selected_holidays = holidays %>%  dplyr::filter(country %in% unique(tt$country))

load(str_c(IO$out_Rdata,"birth_data.Rdata"), verbose = TRUE)

pa = read_feather(path = str_c(IO$output_clue,"pop_indicators/relative_sexual_indicators_detrended_monthly.feather"))

```




```{r results_sex stacked plots, fig.width=10, fig.height=10}

for(Country_Area in unique(tt$country_area)){
  
  Country = unique(tt$country[tt$country_area == Country_Area])
  Area = unique(tt$area[tt$country_area == Country_Area])
  
  
  # Birth data
  
  this_birth = birth %>% dplyr::filter(country == Country, (area == Area) | (area == "Whole country"))
  max_date = max(this_birth$date)
  if(month(max_date)<6){max_year = year(max_date)-1}else{max_year = year(max_date)}
  date_range = c(str_c(max_year - 2,"-07-01"),str_c(max_year,"-07-01")) %>%  as.Date
  
  this_birth_last_2_years = this_birth %>% dplyr::filter( date >= min(date_range), date < max(date_range))
  
  g_birth = ggplot(this_birth_last_2_years, aes(x = date, y = births, 
                                                col = area,
                                                group = interaction(source, area, reliability)))+
    geom_line()+
    scale_x_date(limits = date_range, expand = c(0,0))+
    ggtitle(str_c("Births - ",Country_Area))+
    facet_grid(area ~ ., scale = "free")
  g_birth
  
  # Shifted Birth data (= conceptions)
  
  this_conception_last_2_years = this_birth %>% mutate(date = date - months(8)) %>% 
    dplyr::filter( date >= min(date_range), date < max(date_range))
  
  g_conception = ggplot(this_conception_last_2_years, aes(x = date, y = births, 
                                                          col = area,
                                                          group = interaction(source, area, reliability)))+
    geom_line()+
    facet_grid(area ~ ., scale = "free")+
    ggtitle("Shifted births (conceptions)")+
    scale_x_date(limits = date_range, expand = c(0,0))
  g_conception
  
  
  # Monthly aggregate sexual patterns
  
  this_pa = pa %>% dplyr::filter(country_area == Country_Area, BC == "F")
  
  g_sex_monthly = ggplot(this_pa, aes(x =  date, y = detrended_r_unprot, col = area))+
    geom_hline(yintercept = 0, col = "gray80")+
    geom_line()+
    scale_x_date(limits = c(as.Date("2017-06-30"),as.Date("2019-07-01")),expand = c(0,0))+
    facet_grid(area ~ ., scale = "free")
  g_sex_monthly
  
  
  # Sexual patterns
  
  this_tt = tt %>%   dplyr::filter(country_area == Country_Area, date >= as.Date("2017-07-01"))
  this_holidays =  holidays %>%  dplyr::filter(country == Country)
  
  
  g_typical = ggplot(this_tt, aes(x = date, y = r_sex_country_typical, col = area))+ 
    geom_vline(data = this_holidays, aes(xintercept = date), linetype = 1, col = "gold")+
    geom_text(data = this_holidays, aes(x = date, y = Inf, label = date_str), 
              hjust = 0, nudge_x = 1, vjust = 1, nudge_y = 0, col = "gold3", size = 3, check_overlap = TRUE)+
    geom_line()+
    ggtitle("Total # of sex; overal + weekly trends removed")+
    ylab("Detrended sex")+
    facet_grid(area ~ ., scale = "free")+
    scale_color_manual(values = c(rep("gray40",1),"coral1","slategray1"))+
    scale_x_date(limits = c(as.Date("2017-06-30"),as.Date("2019-07-01")),expand = c(0,0))
  
  g_typical
  
 
  
  
  plotlist = list(g_birth, g_conception, g_sex_monthly, g_typical)
  
  g = plot_grid(plotlist = plotlist, ncol=1, align="v")
  print(g)
  
}



```

