---
title: "Detecting seasonal patterns - Clue dataset"
author: "Laura Symul"
date: "4/18/2019"
output: html_document
---

```{r seasonality_detect_clue setup, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
source("Scripts/00_setup.R")
```


## Clue dataset



### Detecting Seasonality in individual indicators


```{r seasonality_detect_clue load data for indiv indicators, cache = FALSE}
load(paste0(IO$output_clue,"indiv_indicators.Rdata"), verbose = TRUE)
colnames(indiv_indicators)
```




```{r seasonality_detect_clue wavelet analysis on indiv indicators}

for(user in unique(indiv_indicators$user_id)[1:20]){
  
  this_user_indiv_indicators = indiv_indicators[indiv_indicators$user_id == user,]
  this_user_indiv_indicators = this_user_indiv_indicators[order(this_user_indiv_indicators$time_num),]
  
  if(!all(this_user_indiv_indicators$fertility == 0)){
    
    timeserie_matrix = as.matrix(this_user_indiv_indicators[,c("time_num","daily_fertility")])
    
    current.wt = wt(timeserie_matrix, 
                    dt = par$dt, dj = 15*par$dt, 
                    lag1 = 0.7, # pink noise
                    sig.test = 1) # we want to run a significance test
    
    plot(current.wt, main = paste0(user," - daily_fertility"))
    
    timeserie_matrix = as.matrix(this_user_indiv_indicators[,c("time_num","fertility")])
    
    current.wt = wt(timeserie_matrix, 
                    dt = par$dt, dj = 15*par$dt, 
                    lag1 = 0.7, # pink noise
                    sig.test = 1) # we want to run a significance test
    
    plot(current.wt, main = paste0(user," - fertility"))
  }
}


```




### Detecting Seasonality in population indicators



```{r seasonality_detect_clue load data for population indicators, cache = FALSE}
load(paste0(IO$output_clue,"pop_indicators.Rdata"), verbose =  TRUE)
```



```{r seasonality_detect_clue wavelet analysis on population indicators}


pop_indicators$seasonal = NA
pop_indicators$seasonal_power = NA


agg_col_combinations = unique(pop_indicators[,par$agg_col])
for(i in 1:ncol(agg_col_combinations)){
  agg_col_combinations[,i] = as.character(agg_col_combinations[,i])
}

for(i in 1:nrow(agg_col_combinations)){
  cat(paste(agg_col_combinations[i,]),"\n")
  cond = rep(TRUE, nrow(pop_indicators))
  for(agg_col in par$agg_col){  
    eval(parse(text = paste0("cond = cond & (pop_indicators$",agg_col," == agg_col_combinations$",agg_col,"[i])")))
  }
  i_cond = which(cond)
  if(length(i_cond)>0){
    cat("doing the analysis \n")
    this_pop_indicators = pop_indicators[i_cond,]
    
    valid_times = which(this_pop_indicators$n_users > 0)
    this_pop_indicators = this_pop_indicators[valid_times, ]
    time = this_pop_indicators$time_num
    
    # daily fertility
    seasonal_analysis = detect_seasonal_pattern(
      time = time, signal = this_pop_indicators$daily_fertility, title = "daily fertility")
    
    # daily fertility
    seasonal_analysis = detect_seasonal_pattern(
      time = time, signal = this_pop_indicators$fertility, title = "fertility")
  }
}






```





```{r test seasonality detection function detect_seasonal_pattern}

set.seed(2)
# generating 3 years of data
time = seq(0,3 - 1/365, by = 1/365)
#seasonal = 1*cos(time * 2 * pi)
seasonal = 2*rep(lowess(rep(rnorm(365, sd =4),3), f = 1/8)$y[366:730],3)
trend = 10*smooth.spline(rnorm(length(time), sd =4), df = 4)$y
remainder = 2.5*rnorm(length(time))

signal = seasonal+trend+remainder
signal_ts = ts(signal, frequency = 365)

plot(ts(trend, frequency = 365))
plot(signal_ts)

seasonal_analysis = detect_seasonal_pattern(time = time, signal = signal, title = "test")

stl_signal = stl(signal_ts, s.window = "periodic")
plot(stl_signal)

plot(time, stl_signal$time.series[,2],type = "l",col = "blue", 
     ylim = range(stl_signal$time.series[,2],seasonal_analysis$time_series$trend,trend))
points(time, seasonal_analysis$time_series$trend, type= "l", col = "black")
points(time, trend, type= "l", col = "green3")


plot(seasonal_analysis$time_series$time, seasonal_analysis$time_series$detrended_signal, type = "l")


plot(seasonal_analysis$time_series$time, seasonal_analysis$time_series$signal, type = "l")
points(seasonal_analysis$time_series$time, seasonal_analysis$time_series$trend, type = "l", col = "green", lwd = 2)

plot(seasonal_analysis$time_series$time, seasonal_analysis$time_series$detrended_signal, type = "l", col = "green")
points(seasonal_analysis$time_series$time, seasonal_analysis$time_series$seasonal_trend, type = "l", col = "blue", lwd = 2)

plot(seasonal_analysis$time_series$time, seasonal_analysis$time_series$remainder, type = "l", col = "blue")



plot(time, trend, type = "l", col = "green", lwd = 2)
points(seasonal_analysis$time_series$time, seasonal_analysis$time_series$trend, type = "l")

plot(time, seasonal, type = "l", col = "green", lwd = 2)
points(seasonal_analysis$time_series$time, seasonal_analysis$time_series$seasonal_trend, type = "l")

plot(time, remainder, type = "l", col = "green", lwd = 2)
points(seasonal_analysis$time_series$time, seasonal_analysis$time_series$remainder, type = "l")


par(pty="s")

plot(seasonal_analysis$time_series$trend, trend, cex = 0.5, pch = 16)
abline(a = 0, b = 1, col = "green3", lty = 2)

plot(seasonal_analysis$time_series$seasonal_trend, seasonal, cex = 0.5, pch = 16)
abline(a = 0, b = 1, col = "green3", lty = 2)

plot(seasonal_analysis$time_series$remainder, remainder, cex = 0.5, pch = 16)
abline(a = 0, b = 1, col = "green3", lty = 2)




```



```{r test with wt and stl}


# generating 6 years of data
time = seq(0,6, by = 1/365)
seasonal = 1*cos(time * 2 * pi)
trend = 100*smooth.spline(rnorm(length(time), sd =3), df = 5)$y
remainder = 3*rnorm(length(time))

signal = seasonal+trend+remainder
signal_ts = ts(signal, frequency = 365)

plot(ts(trend, frequency = 365))
plot(signal_ts)

signal_stl = stl(signal_ts, s.window = "periodic", robust=TRUE, inner=1, outer=15, na.action=na.fail)
summary(signal_stl)
plot(signal_stl)

detrended_signal = apply(signal_stl$time.series[,c(1,3)],1,sum)
detrended_signal_ts = ts(detrended_signal, frequency = 365)


# using the full 6 years
is_seasonal = wavelet_analysis(time = time, signal = signal, title = "6 days")
is_seasonal


# using the detrended full 6 years
plot(detrended_signal_ts)
is_seasonal = wavelet_analysis(time = time, signal = detrended_signal, title = "6 days, detrended")
is_seasonal


# using 3 first years
time_3d = time[time<3]
signal_3d = signal[time<3]
signal_3d_ts = ts(signal_3d, frequency = 365)
plot(signal_3d_ts)
is_seasonal = wavelet_analysis(time = time_3d, signal = signal_3d, title = "3 days")
is_seasonal


# using the detrended 3 first years
signal_3d_stl = stl(signal_3d_ts, s.window = "periodic", robust=TRUE, inner=1, outer=15, na.action=na.fail)
summary(signal_3d_stl)
plot(signal_3d_stl)

detrended_signal_3d = apply(signal_3d_stl$time.series[,c(1,3)],1,sum)
detrended_signal_3d_ts = ts(detrended_signal_3d, frequency = 365)

plot(detrended_signal_3d_ts)
is_seasonal = wavelet_analysis(time = time_3d, signal = detrended_signal_3d, title = "3 days, detrended")
is_seasonal



```





