---
title: "bigger subset of the clue data"
author: "Laura Symul"
date: "11/27/2019"
output: html_document
---


```{r data_prep_clue setup, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
source("Scripts/00_setup.R")
```

```{r create the folder}


large_subset_folder = paste0(IO$r_Data,"Clue_large_subset_US_BR_EU/input/")
if(!dir.exists(large_subset_folder)){dir.create(large_subset_folder, recursive = TRUE)}

```




```{r load full users and select all users from our favorite countries}
users = read_feather(path = paste0(IO$r_Data,"Clue/input/users.feather"))
dim(users)

selected_country_areas = c("France","United Kingdom","Brazil - Central-West", "Brazil - Northeast", "United States - California","United States - Northeast")
users = users %>% filter(country_area %in% selected_country_areas)
dim(users)

write_feather(users, path = paste0(large_subset_folder, "users.feather"))
```


```{r birth control table}

BC = read_feather(path = paste0(IO$r_Data,"Clue/input/birth_control.feather"))
dim(BC)

BC = BC %>% filter(user_id %in% users$user_id)
dim(BC)

write_feather(BC, path = paste0(large_subset_folder, "birth_control.feather"))

```


```{r cycles tables}

input_folder = paste0(IO$r_Data,"Clue/input/cycles/")
files = list.files(input_folder)

output_folder = paste0(large_subset_folder, "cycles/")
if(!dir.exists(output_folder)){dir.create(output_folder)}

ok = foreach(file = files) %do% {
  cat(file,"\n")
  cycle = read_feather(path = str_c(input_folder,file))
  dim(cycle)
  cycle = cycle %>% filter(user_id %in% users$user_id)
  dim(cycle)
  write_feather(cycle, path = paste0(output_folder, file))
}

```



```{r tracking tables}

input_folder = paste0(IO$r_Data,"Clue/input/tracking/")
files = list.files(input_folder)

output_folder = paste0(large_subset_folder, "tracking/")
if(!dir.exists(output_folder)){dir.create(output_folder)}

ok = foreach(file = files) %do% {
  cat(file,"\n")
  tracking = read_feather(path = str_c(input_folder,file))
  dim(tracking)
  tracking = tracking %>% filter(user_id %in% users$user_id)
  dim(tracking)
  write_feather(tracking, path = paste0(output_folder, file))
}

```



