---
title: "Unmasking Seasonal Cycles in Human Fertility: How holiday sex and fertility cycles shape birth seasonality"
subtitle: "Supplementary Materials"
author: "Symul L., Hsieh P., Shea A., Moreno C.R.C., Skene D.J., Holmes S., Martinez M."
date: "" #`r format(Sys.time(), '%d %B, %Y')`
output: 
  bookdown::pdf_document2:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
    df_print: kable
    highlight: tango
    latex_engine: xelatex
mainfont: Avenir Next
sansfont: Helvetica
monofont: Arial Narrow
fontsize: 10pt
urlcolor: NavyBlue
fig_width: 7
fig_height: 5
abstract: |
  This document contains additional text (Expanded Introduction, Results and Discussion), an overview of the Materials and Methods and the pdf-rendering of all analyses performed for the manuscript "Unmasking Seasonal Cycles in Human Fertility: How holiday sex and fertility cycles shape birth seasonality". The R markdown (.Rmd) files used to generate this pdf can be found on [github](https://github.com/lasy/Seasonality-Public-Repo) ([https://github.com/lasy/Seasonality-Public-Repo](https://github.com/lasy/Seasonality-Public-Repo)). Each section is a standalone Rmd file and can be run separately. The data for each section is available on the same github repository except for the sections "App data processing and filtering" and "App data aggregation" as the raw App data cannot be shared publicly to respect users' privacy and data ownership.
header-includes:
  - \renewcommand{\abstractname}{}
  - \let\counterwithout\relax
  - \let\counterwithin\relax
  - \usepackage{chngcntr}
  - \usepackage{float}
  - \floatplacement{figure}{H}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable} 
  - \usepackage{threeparttablex} 
  - \usepackage[normalem]{ulem} 
  - \usepackage{makecell}
  - \usepackage{xcolor}
keywords:
  - human birth seasonality
  - sexual behavior
linestretch: 1
geometry: "left=2cm, right=2cm, top=1.5cm, bottom=1.5cm"
bibliography: seasonality_suppl_bibliography.bib
csl: science.csl
---


```{r changing size of R code, include = FALSE, eval = TRUE}
# def.chunk.hook = knitr::knit_hooks$get("chunk")
# knitr::knit_hooks$set(chunk = 
#                         function(x, options) {
#   x <- def.chunk.hook(x, options)
#   ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
# })
```


\newpage


\listoftables


\listoffigures


```{r seasonality setup, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, fig.align = 'center')
source("Scripts/00_setup.R")
```


\newpage

```{r child = '1_expanded_text.Rmd', cache=TRUE}
```


\newpage

```{r child = '2_methods_overview.Rmd', cache=TRUE}
```

\newpage

```{r child = '3_births_data_processing.Rmd', cache=TRUE}
```

\newpage

```{r child = '4_app_data_processing_and_filtering.Rmd', cache=TRUE}
```

\newpage

```{r child = '5_app_data_aggregation.Rmd', cache=TRUE}
```

\newpage

```{r child = '6_births_models.Rmd', cache=TRUE}
```

\newpage

```{r child = '7_checking_for_reporting_bias.Rmd', cache=TRUE}
```

\newpage


```{r child = '10_FIGURES.Rmd', cache=TRUE}
```

\newpage


# Reproducibility receipt {-}

```{r repro_receipt, echo = FALSE, eval = TRUE, cache = FALSE, results='markup'}

cat("Execution datetime:\n")
print(Sys.time())
cat("-------------------------------")
cat("sessionInfo :\n\n\n")

sessionInfo()

```


\newpage

# References
